### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'in_dim'

### ISSUE THREAD

**Issue by deeemoney** [TencentARC/VQFR#30]
Hi, I get an error when I run the v1 model reasoner. What should I do.

Traceback (most recent call last):
  File "/root/autodl-fs/VQFR/demo.py", line 153, in <module>
    main()
  File "/root/autodl-fs/VQFR/demo.py", line 102, in main
    restorer = VQFR_Demo(model_path=model_path, upscale=args.upscale, arch=arch, bg_upsampler=bg_upsampler)
  File "/root/autodl-fs/VQFR/vqfr/demo_util.py", line 36, in __init__
    self.vqfr = VQFRv1(
  File "/root/autodl-fs/VQFR/vqfr/archs/vqfrv1_arch.py", line 188, in __init__
    self.quantizer = GeneralizedQuantizer(quantizer_opt)
  File "/root/autodl-fs/VQFR/vqfr/archs/vqganv1_arch.py", line 177, in __init__
    self.quantize_dict[level_name] = build_quantizer(level_opt)
  File "/root/autodl-fs/VQFR/vqfr/archs/quantizer_arch.py", line 19, in build_quantizer
    quantizer = QUANTIZER_REGISTRY.get(quantizer_type)(**opt)
TypeError: __init__() got an unexpected keyword argument 'in_dim'

**Comment by wizaaaard** [comment]
You can change the value of the key: 'type' in options/train/VQFR/train_vqfr_v1_B16_200K.yml line 108, from L2VectorQuantizer to L2VectorQuantizerKmeans. Then it will be ok, I suppose.

**Comment by wizaaaard** [comment]
> You can change the value of the key: 'type' in options/train/VQFR/train_vqfr_v1_B16_200K.yml line 108, from L2VectorQuantizer to L2VectorQuantizerKmeans. Then it will be ok, I suppose.
